#Setup LAMP Stack
- hosts: tag_Type_WebServer
  tasks:
    - name: install Apache
      become: yes
      yum: name={{ item }} state=present
      with_items:
        - httpd
    - name: start services
      service: name={{ item }} state=running enabled=yes
      become: yes
      with_items:
        - httpd
    - name: deploy index.html
      become: yes
      unarchive:
        src: /etc/ansible/blog.tar.gz
        dest: /var/www/html
        extra_opts: [--strip-components=1]
        selevel: s0
        setype: httpd_sys_content_t
      #copy: src=/etc/ansible/blog.zip dest=/var/www/html/index.html
      #copy: src=/etc/ansible/blog/ dest=/var/www/html/ remote_src=yes directory_mode=yes
      #command: cp -r /etc/ansible/blog/* /var/www/html/
