---
#Setup LAMP Stack
- hosts: tag_Type_WebServer
  tasks:
    - name: install Apache
      become: yes
      yum: name={{ item }} state=present
      with_items:
        - httpd
    - name: start services
      service: name={{ item }} state=started enabled=yes
      become: yes
      with_items:
        - httpd
    - name: add authorized keys
      authorized_key:
        user: ec2-user
        state: present
        key: https://github.com/anigoza-card.keys
      with_items:
        - https://github.com/anigoza-card.keys
        - https://github.com/aubreynigoza.keys
    - name: deploy index.html
      become: yes
      unarchive:
        src: ~/repo/sandbox-worms-infrastructure/ansible/blog.tar.gz
        #src: /etc/ansible/blog.tar.gz
        dest: /var/www/html
        extra_opts: [--strip-components=1]
        selevel: s0
        setype: httpd_sys_content_t
        owner: apache
        group: apache
        mode: 0755
        list_files: yes
      #copy: src=/etc/ansible/blog.zip dest=/var/www/html/index.html
      #copy: src=/etc/ansible/blog/ dest=/var/www/html/ remote_src=yes directory_mode=yes
      #command: cp -r /etc/ansible/blog/* /var/www/html/
